version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  lint:
    steps:
      - checkout
      - node/install-packages
      - run:
        command: npm run lint
workflows:
  node-tests:
    jobs:
      - lint
      - node/test
